language: php

sudo: false

php:
  - 7.1
  - 7.1snapshot
  - 7.2
  - 7.2snapshot
  - master

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer update

script:
  - phpunit --configuration=phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
email: false
